name: CI-CD

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: DVC Pull
        run: |
          dvc pull -v

      - name: Run Appllication
        run: |
          nohup streamlit run app.py --server.port 8000 &
          sleep 30

      - name: Test App
        run: |
          pytest test_app.py

      - name: Stop Streamlit app
        run: |
          pkill -f "streamlit run"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 385105852594.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build docker image
        run: |
          docker build -t songs_reco_sys:latest .

      - name: Tag docker image
        run: |
          docker tag songs_reco_sys:latest 385105852594.dkr.ecr.ap-south-1.amazonaws.com/songs_reco_sys:latest

      - name: Push docker image to ECR
        run: |
          docker push 385105852594.dkr.ecr.ap-south-1.amazonaws.com/songs_reco_sys:latest
      - name: Deploy to AWS EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ap-south-1
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 385105852594.dkr.ecr.ap-south-1.amazonaws.com
            docker stop songs_reco_app || true
            docker rm songs_reco_app || true
            docker system prune -af --volumes
            docker pull 385105852594.dkr.ecr.ap-south-1.amazonaws.com/songs_reco_sys:latest
            docker run -d --name songs_reco_app -p 80:8000 385105852594.dkr.ecr.ap-south-1.amazonaws.com/songs_reco_sys:latest